// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACxBCKIwTl9dbxN4juuuiimHBo2b5_I4',
    appId: '1:234290766783:web:cf1ce1d67ef8b6d6ee770a',
    messagingSenderId: '234290766783',
    projectId: 'flood-disaster-app',
    authDomain: 'flood-disaster-app.firebaseapp.com',
    storageBucket: 'flood-disaster-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyk9mDfMMD1TL7seyZH4i50SubpaJf9g',
    appId: '1:234290766783:android:2422a436574bcc6cee770a',
    messagingSenderId: '234290766783',
    projectId: 'flood-disaster-app',
    storageBucket: 'flood-disaster-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYM1JOcK0w8Ks1xypFRZFU6KAHe_Mk2_U',
    appId: '1:234290766783:ios:7a6e06cb99610e51ee770a',
    messagingSenderId: '234290766783',
    projectId: 'flood-disaster-app',
    storageBucket: 'flood-disaster-app.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYM1JOcK0w8Ks1xypFRZFU6KAHe_Mk2_U',
    appId: '1:234290766783:ios:7a6e06cb99610e51ee770a',
    messagingSenderId: '234290766783',
    projectId: 'flood-disaster-app',
    storageBucket: 'flood-disaster-app.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACxBCKIwTl9dbxN4juuuiimHBo2b5_I4',
    appId: '1:234290766783:web:db017a2733908e50ee770a',
    messagingSenderId: '234290766783',
    projectId: 'flood-disaster-app',
    authDomain: 'flood-disaster-app.firebaseapp.com',
    storageBucket: 'flood-disaster-app.firebasestorage.app',
  );

}